apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: otel-app
  namespace: auto-rollback
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/jessesuen/otel-app
      imageSelectionStrategy: SemVer
